tap "ngrok/ngrok", trusted: { casks: ["ngrok"] }
tap "stripe/stripe-cli"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# GitHub command-line tool
brew "gh"
# Improved top (interactive process viewer)
brew "htop"
# Tool to capture still images from an iSight or other video source
brew "imagesnap"
# Object-relational database system
brew "postgresql@18", restart_service: :changed, link: true
# Ruby version manager
brew "rbenv"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Image processing library
brew "vips"
# Stripe CLI utility
brew "stripe/stripe-cli/stripe", trusted: true
vscode "aaron-bond.better-comments"
vscode "anysphere.remote-ssh"
vscode "bradlc.vscode-tailwindcss"
vscode "damolinx.damolinx-bookmarks"
vscode "eamodio.gitlens"
vscode "mechatroner.rainbow-csv"
