theme = "catppuccin"
visualizer = "Butterfly"
show_metadata = false
eq_preset = "Custom"
eq = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
shuffle = false
speed = 1.00

[radio]
country = "none"

[ytmusic]
cookies_from = "chrome"
