theme = "catppuccin-latte"
visualizer = "Geyser"
show_metadata = false
eq_preset = "Flat"
eq = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
shuffle = true
speed = 1.00

[radio]
country = "none"

[ytmusic]
cookies_from = "chrome"
