[[entry]]
favorited_at = "2026-09-13T15:27:03Z"
path = "https://icecast-rian.cdnvideo.ru/voicerus"
title = "Спутник [128k] · Russian Federation"
genre = "news,talk"
realtime = true
provider_meta.radio.country = "The Russian Federation"
provider_meta.radio.codec = "MP3"
provider_meta.radio.bitrate = "128"
provider_meta.radio.state = "Москва"
